/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuctionSchema } from './auctionSchema';
import { UserSchema } from './userSchema';


export interface BidTransactionSchema { 
    guid: string;
    created: string;
    updated: string;
    is_active: boolean;
    auction?: AuctionSchema;
    user?: UserSchema;
    amount?: number;
    has_won?: boolean;
}

