/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type ErrorCodes = 1001 | 1002 | 1003 | 1004 | 1005 | 1006 | 1007 | 1008 | 1009 | 1010 | 2001 | 3001 | 4001 | 5001;

export const ErrorCodes = {
    NUMBER_1001: 1001 as ErrorCodes,
    NUMBER_1002: 1002 as ErrorCodes,
    NUMBER_1003: 1003 as ErrorCodes,
    NUMBER_1004: 1004 as ErrorCodes,
    NUMBER_1005: 1005 as ErrorCodes,
    NUMBER_1006: 1006 as ErrorCodes,
    NUMBER_1007: 1007 as ErrorCodes,
    NUMBER_1008: 1008 as ErrorCodes,
    NUMBER_1009: 1009 as ErrorCodes,
    NUMBER_1010: 1010 as ErrorCodes,
    NUMBER_2001: 2001 as ErrorCodes,
    NUMBER_3001: 3001 as ErrorCodes,
    NUMBER_4001: 4001 as ErrorCodes,
    NUMBER_5001: 5001 as ErrorCodes
};

