/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type UserTypeEnum = 'ATTN' | 'ADMIN' | 'BUYER' | 'SELLER';

export const UserTypeEnum = {
    Attn: 'ATTN' as UserTypeEnum,
    Admin: 'ADMIN' as UserTypeEnum,
    Buyer: 'BUYER' as UserTypeEnum,
    Seller: 'SELLER' as UserTypeEnum
};

