/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuctionSchema } from './auctionSchema';


export interface AuctionListSchema { 
    count: number;
    next_page?: number;
    previous_page?: number;
    total_pages: number;
    data: Array<AuctionSchema>;
}

