/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsoleHomeDataSchema { 
    total_products: number;
    total_verified_products: number;
    total_on_process_products: number;
    total_running_auctions: number;
    total_bids: number;
}

