/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuctionSchema } from './auctionSchema';
import { CreditSchema } from './creditSchema';
import { BidTransactionSchema } from './bidTransactionSchema';
import { CreditTransactionTypeChoices } from './creditTransactionTypeChoices';


export interface CreditTransactionSchema { 
    guid: string;
    created: string;
    updated: string;
    is_active: boolean;
    credit: CreditSchema;
    amount?: number;
    type: CreditTransactionTypeChoices;
    auction?: AuctionSchema;
    description?: string;
    bid_transaction?: BidTransactionSchema;
}

