/**
 * Auction Core API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSchema } from './productSchema';
import { ProfileSchema } from './profileSchema';


export interface ProductReviewSchema { 
    product: ProductSchema;
    rates?: number;
    comment?: string;
    is_reported?: boolean;
    profile: ProfileSchema;
}

